dist: trusty
sudo: required
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive
- sudo apt-get -qq update && sudo apt-get install -y texlive
script: make
deploy:
  provider: releases
  api_key:
    secure: gyJQMYWIuyVlIlPlRH/dgIeNuiOP0Ye1mCFT+lcP0O7c1HuTILfe4ZN4PgLtBvKKj8/DbZYL/ZHNiTn1u2GXI9CuTKGDaRywvtUzbibq4GRh3kh3EJuqDAuKKrdHGkJz8Ni++samCU2571evJwqJ5jFGPfx6lJ3I++3E0UFv6gCc/eQIUi39H1T28P4XvE516U9zWdfoH8j6017vJeTy/dCH9rhy+6wCWbN1Azb4gE160bSnfXx0Wlsgg6LED9/QGBva8AMZZ7V51gz4xs79TCIVfy4phVkbGpLSDayliaXvFN7Etad+6/AXGy9haAa/5aHLQLm3IH38dTqQgEsdmeqzlX2rXapj8hgMzYSV725cxAgcS2YWjajhvPrHQQkZbquHq9qIIC4sEcOznHN8YK1A98Kpox27eN5habACSHIgajIHsr91qgyTzxFjwzNWZk5nOQpVG0V9JxGE8ufxVVg9IrA8bYviJI0NugVJbdxrgofdZqy/b3XtrVi5K++03saf9fJxjUxgbLoDUuSdmebBrBcf/Esi7xhhdghFvlHprjis0Sjp4XdCBg6LGSra57SCnPo3p8WNVnX3T4r2WPbrFDodrdCUZjAgqbqUEWMTTqcJAcKEBEU2XApoYaBQbnM96nzPTbpuLElSz/zyyyS/ilXLbJ1bCh/djdJ/VqU=
  file: tex/_build/main.pdf
  skip_cleanup: true
  on:
    repo: wisebaldone/subject-guide